Update Jenkinsfile

diff --git a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/Jenkinsfile b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/Jenkinsfile
--- a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/Jenkinsfile
+++ b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/Jenkinsfile
@@ -21,24 +21,24 @@ pipeline {
 
         stage('Build and Test') {
             steps {
-                echo "===== Debug: Checking Java files and main class ====="
-                sh 'ls -ltr src/main/java/com/abhishek/'
-                sh 'head -n 20 src/main/java/com/abhishek/StartApplication.java'
-                sh 'grep -A 2 "<mainClass>" pom.xml || echo "No main class defined in pom.xml"'
+                dir('java-maven-sonar-argocd-helm-k8s/spring-boot-app') {
+                    echo "===== Debug: Checking Java files and main class ====="
+                    sh 'ls -ltr src/main/java/com/abhishek/'
 
-                script {
-                    def status = sh(script: '''
-                        set -o errexit
-                        set -o pipefail
-                        set -x
-                        mvn clean package -X
-                    ''', returnStatus: true)
+                    script {
+                        def status = sh(script: '''
+                            set -o errexit
+                            set -o pipefail
+                            set -x
+                            mvn clean package -X
+                        ''', returnStatus: true)
 
-                    if (status != 0) {
-                        echo "Build failed with exit code ${status}"
-                        error("Stopping pipeline due to build failure")
-                    } else {
-                        echo "Build succeeded"
+                        if (status != 0) {
+                            echo "Build failed with exit code ${status}"
+                            error("Stopping pipeline due to build failure")
+                        } else {
+                            echo "Build succeeded"
+                        }
                     }
                 }
             }
@@ -46,17 +46,19 @@ pipeline {
 
         stage('Static Code Analysis - SonarCloud') {
             when {
-                expression { fileExists('pom.xml') }
+                expression { fileExists('java-maven-sonar-argocd-helm-k8s/spring-boot-app/pom.xml') }
             }
             steps {
-                withCredentials([string(credentialsId: 'sonarcloud-token', variable: 'SONAR_AUTH_TOKEN')]) {
-                    sh """
-                        mvn sonar:sonar \
-                        -Dsonar.organization=Harbey-tech \
-                        -Dsonar.projectKey=Harbey-tech \
-                        -Dsonar.login=${SONAR_AUTH_TOKEN} \
-                        -Dsonar.host.url=${SONAR_URL}
-                    """
+                dir('java-maven-sonar-argocd-helm-k8s/spring-boot-app') {
+                    withCredentials([string(credentialsId: 'sonarcloud-token', variable: 'SONAR_AUTH_TOKEN')]) {
+                        sh """
+                            mvn sonar:sonar \
+                            -Dsonar.organization=Harbey-tech \
+                            -Dsonar.projectKey=Harbey-tech \
+                            -Dsonar.login=${SONAR_AUTH_TOKEN} \
+                            -Dsonar.host.url=${SONAR_URL}
+                        """
+                    }
                 }
             }
         }
@@ -64,10 +66,12 @@ pipeline {
         stage('Build and Push Docker Image') {
             steps {
                 script {
-                    sh "docker build -t ${DOCKER_IMAGE} ."
-                    def dockerImage = docker.image("${DOCKER_IMAGE}")
-                    docker.withRegistry('https://index.docker.io/v1/', 'docker-cred') {
-                        dockerImage.push()
+                    dir('java-maven-sonar-argocd-helm-k8s/spring-boot-app') {
+                        sh "docker build -t ${DOCKER_IMAGE} ."
+                        def dockerImage = docker.image("${DOCKER_IMAGE}")
+                        docker.withRegistry('https://index.docker.io/v1/', 'docker-cred') {
+                            dockerImage.push()
+                        }
                     }
                 }
             }
@@ -80,15 +84,17 @@ pipeline {
             }
             steps {
                 withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
-                    sh """
-                        git config user.email "harbey2965@gmail.com"
-                        git config user.name "Harbey-tech"
-                        BUILD_NUMBER=${BUILD_NUMBER}
-                        sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" deployment.yaml
-                        git add deployment.yaml
-                        git commit -m "Update deployment image to version ${BUILD_NUMBER}"
-                        git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
-                    """
+                    dir('java-maven-sonar-argocd-helm-k8s/spring-boot-app') {
+                        sh """
+                            git config user.email "harbey2965@gmail.com"
+                            git config user.name "Harbey-tech"
+                            BUILD_NUMBER=${BUILD_NUMBER}
+                            sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" deployment.yaml
+                            git add deployment.yaml
+                            git commit -m "Update deployment image to version ${BUILD_NUMBER}"
+                            git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
+                        """
+                    }
                 }
             }
         }
